apiVersion: v1
kind: Pod                                                                                                                                                                                                                                    
metadata:                                                                                                                                                                                                                                    
  name: client
  labels:                                                                                                                                                                                                                                    
    app: client
spec:                                                                                                                                                                                                                                        
  containers:                                                                                                                                                                                                                                
    - name: client
      image: rastislavszabo/client
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"