apiVersion: v1
kind: Service
metadata:
  name: test-server
  labels:
    run: test-server
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
  - port: 6443


---
apiVersion: v1
kind: Pod                                                                                                                                                                                                                                    
metadata:                                                                                                                                                                                                                                    
  name: server                                                                                                                                                                                                           
  labels:                                                                                                                                                                                                                                    
    app: server                                                                                                                                                                                                                         
spec:                                                                                                                                                                                                                                        
  containers:                                                                                                                                                                                                                                
    - name: server                                                                                                                                                                                                                 
      image: rastislavszabo/server
      imagePullPolicy: IfNotPresent
      ports:                                                                                                                                                                                                                                 
        - containerPort: 6443 
